apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kube-projekt.fullname" . }}
  labels:
    {{ include "kube-projekt.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "kube-projekt.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "kube-projekt.fullname" . }}
    spec:
      containers:
        - name: kube-projekt
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10

